/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author cristopher
 */
public class OpcionesFrame extends javax.swing.JFrame {

    /**
     * Creates new form OpcionesFrame
     */
    public OpcionesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSoundtrack = new javax.swing.JButton();
        btnSfx = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSoundtrack.setForeground(new java.awt.Color(51, 51, 51));
        btnSoundtrack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonRec.png"))); // NOI18N
        btnSoundtrack.setText("Soundtrack: On");
        btnSoundtrack.setContentAreaFilled(false);
        btnSoundtrack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btnSoundtrack, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 220, 30));

        btnSfx.setForeground(new java.awt.Color(51, 51, 51));
        btnSfx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonRec.png"))); // NOI18N
        btnSfx.setText("SFX: On");
        btnSfx.setContentAreaFilled(false);
        btnSfx.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btnSfx, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 220, 30));

        btnCreditos.setForeground(new java.awt.Color(51, 51, 51));
        btnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/botonRec.png"))); // NOI18N
        btnCreditos.setText("Creditos");
        btnCreditos.setContentAreaFilled(false);
        btnCreditos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(btnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 220, 30));

        btnCerrar.setText("X");
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 18));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creditos_opciones.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnSfx;
    private javax.swing.JButton btnSoundtrack;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
